include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/generated/intl/messages_all.dart
    - lib/generated/intl/messages_de.dart
    - lib/generated/intl/messages_en.dart
    - lib/generated/l10n.dart
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    - use_enums
    - file_names
    - avoid_print
    - close_sinks
    - void_checks
    - valid_regexps
    - package_names
    - empty_catches
    - null_closures
    - use_raw_strings
    - use_colored_box
    - hash_and_equals
    - avoid_empty_else
    - empty_statements
    - unnecessary_this
    - exhaustive_cases
    - package_api_docs
    - overridden_fields
    - only_throw_errors
    - use_decorated_box
    - await_only_futures
    - use_string_buffers
    - prefer_final_locals
    - comment_references
    - use_named_constants
    - secure_pubspec_urls
    - avoid_dynamic_calls
    - cascade_invocations
    - use_super_parameters
    - cancel_subscriptions
    - one_member_abstracts
    - avoid_type_to_string
    - combinators_ordering
    - unreachable_from_main
    - parameter_assignments
    - control_flow_in_finally
    - implementation_imports
    - implicit_call_tearoffs
    - prefer_final_in_for_each
    - no_runtimeType_toString
    - unnecessary_raw_strings
    - unnecessary_parenthesis
    - empty_constructor_bodies
    - constant_identifier_names
    - use_test_throws_matchers
    - use_rethrow_when_possible
    - always_use_package_imports
    - unnecessary_string_escapes
    - avoid_relative_lib_imports
    - use_to_and_as_if_applicable
    - always_declare_return_types
    - join_return_with_assignment
    - non_constant_identifier_names
    - cast_nullable_to_non_nullable
    - dangling_library_doc_comments
    - unnecessary_to_list_in_spreads
    - conditional_uri_does_not_exist
    - use_is_even_rather_than_modulo
    - use_key_in_widget_constructors
    - avoid_types_as_parameter_names
    - avoid_shadowing_type_parameters
    - avoid_returning_null_for_future
    - collection_methods_unrelated_type
    - use_setters_to_change_properties
    - unnecessary_string_interpolations
    - prefer_asserts_in_initializer_lists
    - prefer_adjacent_string_concatenation
    - null_check_on_nullable_type_parameter
    - leading_newlines_in_multiline_strings
    - use_if_null_to_convert_nulls_to_bools
    - use_full_hex_values_for_flutter_colors
    - curly_braces_in_flow_control_structures
    - use_function_type_syntax_for_parameters
    - use_late_for_private_fields_and_variables
    - missing_whitespace_between_adjacent_strings
    - no_leading_underscores_for_local_identifiers